Command:Client.cpp Command.cpp ConcreteCommand1.cpp ConcreteCommand2.cpp ConcreteReceiver1.cpp ConcreteReceiver2.cpp Receiver.cpp Invoker.cpp
	g++ $^ -o $@

clean:
	rm -f Command *.o

run:
	./Command

