Decorator:Client.cpp Decorator.cpp Component.cpp ConcreteComponent.cpp ConcreteDecorator1.cpp ConcreteDecorator2.cpp DecoratorOnlyOne.cpp
	g++ $^ -o $@

clean:
	rm -f Decorator *.o

run:
	./Decorator

